POST http://localhost:2020/api/validate
Authorization: Bearer {{$dotenv DEV_JWT}}

###
POST http://localhost:2020/api/user/login HTTP/1.1
content-type: application/json

{
	"email": "{{$dotenv DEV_USERNAME}}",
	"password": "{{$dotenv DEV_PASSOWRD}}"
}

###
POST http://localhost:2020/api/user/register HTTP/1.1
content-type: application/json

{
	"email": "{{$dotenv DEV_NEW_USERNAME}}",
	"password": "{{$dotenv DEV_NEW_PASSWORD}}"
}